-->> FUNÇÕES <--
--Retorna faturamento por notas buscando os itens que pertencem a nota

USE SUCOS_VENDAS

SELECT SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS] WHERE NUMERO = 100


CREATE FUNCTION FaturamentoNota (@NUMERO AS INT) RETURNS FLOAT
AS
BEGIN
	DECLARE @FATURAMENTO FLOAT
	SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS] 
	WHERE NUMERO = @NUMERO
	RETURN @FATURAMENTO
END

--Conferindo o faturamento de cada nota com a função
SELECT NUMERO, dbo.FaturamentoNota (NUMERO) AS FATURAMENTO FROM [NOTAS FISCAIS]