--> Tratamento de erros com uso de Debug <<--
DROP PROCEDURE TrataErroZeroTry2
CREATE PROCEDURE TrataErroZeroTry2 @CPF VARCHAR(12), @ANO INT, @DENOMINADOR INT,
@MENSAGEM VARCHAR(MAX) OUTPUT

AS
BEGIN
	BEGIN TRY
		SELECT SUM(A.[QUANTIDADE] * A.[PREÇO]) AS FATURAMENTO,
		SUM(A.[QUANTIDADE] * A.[PREÇO]/ @DENOMINADOR) AS COMISSAO 
		FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
		ON A.NUMERO = B.NUMERO 
		WHERE B.CPF = @CPF AND YEAR([DATA]) = @ANO
	END TRY
	BEGIN CATCH
		SET @MENSAGEM = 'Erro número: ' + CONVERT(VARCHAR(10), ERROR_NUMBER()) + ' - ' 
		SET @MENSAGEM = @MENSAGEM + 'Mensagem: ' + ERROR_MESSAGE() + ' - ' 
		SET @MENSAGEM = @MENSAGEM + 'Grau de severidade do erro: ' + CONVERT(VARCHAR(10), ERROR_SEVERITY()) + ' - ' 
		SET @MENSAGEM = @MENSAGEM + 'Estado do erro: ' + CONVERT(VARCHAR(10), ERROR_SEVERITY()) + ' - ' 
		SET @MENSAGEM = @MENSAGEM + 'Número da linha: ' + CONVERT(VARCHAR(10), ERROR_LINE()) + ' - ' 
		SET @MENSAGEM = @MENSAGEM + 'Procedure: ' +  ERROR_PROCEDURE()
	END CATCH 
END		


-- Testando
DECLARE @DENOMINADOR INT
DECLARE @CPF VARCHAR(12)
DECLARE @ANO INT
DECLARE @MENSAGEM VARCHAR(MAX)

SET @CPF = '5576228758'
SET @ANO = 2016
SET @DENOMINADOR = 0
SET @MENSAGEM = ''


--Executando
EXEC TrataErroZeroTry2 @CPF = @CPF, @ANO = @ANO, @DENOMINADOR = @DENOMINADOR, @MENSAGEM = @MENSAGEM OUTPUT

-- Exibe mensagem se houver erro
IF @MENSAGEM <> ''
	PRINT @MENSAGEM