--> LOOP WHILE <--

-- O comando BREAK é usado para parar o loop antes de chegar no final defido no WHILE

DECLARE @LIMITE_MINIMO INT
DECLARE @LIMITE_MAXIMO INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 10

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	PRINT @LIMITE_MINIMO
	SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1
	IF @LIMITE_MINIMO = 6
	BREAK
END
