-->> Procedure para gerar nota fiscal aleatória <<--

CREATE PROCEDURE CriaNotaFiscal @DATA DATE
AS
BEGIN
	DECLARE @CLIENTE VARCHAR(12)
	DECLARE @VENDEDOR VARCHAR(12)
	DECLARE @PRODUTO VARCHAR(12)
	DECLARE @NUMERO INT
	DECLARE @IMPOSTO FLOAT
	DECLARE @NUM_ITENS INT
	DECLARE @CONTADOR INT
	DECLARE @QUANTIDADE INT
	DECLARE @PRECO FLOAT
	-- Não pode ter mais de um item com o mesmo produto na mesma nota, 
	-- se acontecer retorna erro na PK (pode acontecer gerando aleatório)
	-- Essas variaveis verificam se o registro já existe antes de inserir
	DECLARE @LISTA_PRODUTOS TABLE (PRODUTO VARCHAR(20))
	DECLARE @AUX_PRODUTO INT

	SET @CLIENTE = [dbo].[EntidadeAleatoria]('CLIENTE')
	SET @VENDEDOR = [dbo].[EntidadeAleatoria]('VENDEDOR')
	SELECT @NUMERO = MAX(NUMERO) + 2 FROM [NOTAS FISCAIS]
	SET @IMPOSTO = 0.15
	SET @CONTADOR = 1
	SET @NUM_ITENS = [dbo].NumeroAleatorio(2,10)

	INSERT INTO [NOTAS FISCAIS] (CPF, MATRICULA, DATA, NUMERO, IMPOSTO)
	VALUES (@CLIENTE, @VENDEDOR, @DATA, @NUMERO, @IMPOSTO)

	PRINT 'CABEÇARIO'
	PRINT @DATA
	PRINT @CLIENTE
	PRINT @VENDEDOR
	PRINT @IMPOSTO
	PRINT @NUMERO
	PRINT ''
	PRINT 'ITENS'
	WHILE @CONTADOR <= @NUM_ITENS
	BEGIN

		SET @PRODUTO = [dbo].[EntidadeAleatoria]('PRODUTO')
		--Verificando se já existe
		SELECT @AUX_PRODUTO = COUNT(*) FROM @LISTA_PRODUTOS WHERE PRODUTO = @PRODUTO
		IF @AUX_PRODUTO = 0 
		BEGIN
			SET @QUANTIDADE = [dbo].NumeroAleatorio(5,100)
			SELECT @PRECO = [PREÇO DE LISTA] FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = @PRODUTO
			PRINT @NUMERO
			PRINT @PRODUTO
			PRINT @QUANTIDADE
			PRINT @PRECO
			PRINT ''
	
			INSERT INTO [ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PREÇO)
			VALUES(@NUMERO, @PRODUTO, @QUANTIDADE, @PRECO)

			SET @CONTADOR = @CONTADOR + 1
		END	
		-- Alimenta lista caso ainda não exista o produto
		INSERT INTO @LISTA_PRODUTOS (PRODUTO) VALUES (@PRODUTO)
	END
END


--Testando chamada da proc:
EXEC CriaNotaFiscal @DATA = '20200730'