-->> STORED PROCEDURES <<--
USE SUCOS_VENDAS

-- Procedure para buscar Clientes ou Vendores de acordo com nome da entidade

CREATE PROCEDURE BuscaPorEntidade @ENTIDADE AS VARCHAR(10)
AS
BEGIN
IF @ENTIDADE = 'CLIENTE'
	SELECT [CPF] AS IDENTIFICADOR, [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO FROM [TABELA DE CLIENTES]
ELSE IF @ENTIDADE = 'VENDEDORES'
	SELECT [MATRICULA] AS INDENTIFICADOR, [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO FROM [TABELA DE VENDEDORES]
END

--Conferindo
EXEC BuscaPorEntidade @ENTIDADE = 'CLIENTES'
EXEC BuscaPorEntidade @ENTIDADE = 'VENDEDORES'
