-->> TRATAMENTO DE ERROS <<-- 
SELECT SUM(A.[QUANTIDADE] * A.[PREÇO]) AS FATURAMENTO,
SUM(A.[QUANTIDADE] * A.[PREÇO]/10) AS COMISSAO 
FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO 
WHERE B.CPF = '5576228758' AND YEAR([DATA]) = 2016

-- Se o denomidor for zero retornar um erro de divisão
DECLARE @DENOMINADOR  INT 
SET @DENOMINADOR = 0

SELECT SUM(A.[QUANTIDADE] * A.[PREÇO]) AS FATURAMENTO,
SUM(A.[QUANTIDADE] * A.[PREÇO]/ @DENOMINADOR) AS COMISSAO 
FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO 
WHERE B.CPF = '5576228758' AND YEAR([DATA]) = 2016


--> Procedure para verificar e retornar erro
CREATE PROCEDURE TrataErroZero @CPF VARCHAR(12), @ANO INT, @DENOMINADOR INT,
@NUMERO INT OUTPUT, @NUMLINHA INT OUTPUT
AS
BEGIN
	SELECT SUM(A.[QUANTIDADE] * A.[PREÇO]) AS FATURAMENTO,
	SUM(A.[QUANTIDADE] * A.[PREÇO]/ @DENOMINADOR) AS COMISSAO 
	FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
	ON A.NUMERO = B.NUMERO 
	WHERE B.CPF = '5576228758' AND YEAR([DATA]) = 2016
	SELECT @NUMERO = @@ERROR
	SELECT @NUMLINHA = @@ROWCOUNT
END

--> Declarando variaveis para chamar procedure
DECLARE @DENOMINADOR INT
DECLARE @CPF VARCHAR(12)
DECLARE @ANO INT
DECLARE @NUMERO INT
DECLARE @NUMLINHA INT

SET @CPF = '5576228758'
SET @ANO = 2016
SET @DENOMINADOR = 0
 
--Executando
EXEC TrataErroZero @CPF = @CPF, @ANO = @ANO, @DENOMINADOR = @DENOMINADOR,
@NUMERO = @NUMERO OUTPUT, @NUMLINHA = @NUMLINHA OUTPUT

--Retornando mensagem amigavel para erro se houver
IF @NUMERO <> 0
	PRINT 'Houve um erro: ' + CONVERT(VARCHAR(10), @NUMERO) + ' - ' + CONVERT(VARCHAR(3), @NUMLINHA)