-->> Tratamento de erros com Try/Catch <<--
CREATE PROCEDURE TrataErroZeroTry @CPF VARCHAR(12), @ANO INT, @DENOMINADOR INT,
@MENSAGEM VARCHAR(50) OUTPUT

AS
BEGIN
	BEGIN TRY
		SELECT SUM(A.[QUANTIDADE] * A.[PREÇO]) AS FATURAMENTO,
		SUM(A.[QUANTIDADE] * A.[PREÇO]/ @DENOMINADOR) AS COMISSAO 
		FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
		ON A.NUMERO = B.NUMERO 
		WHERE B.CPF = @CPF AND YEAR([DATA]) = @ANO
	END TRY
	BEGIN CATCH
		SET @MENSAGEM = 'Houve um erro: ' + CONVERT(VARCHAR(10), @@ERROR) 
	END CATCH 
END

-- Testando proc

DECLARE @DENOMINADOR INT
DECLARE @CPF VARCHAR(12)
DECLARE @ANO INT
DECLARE @MENSAGEM VARCHAR(50)

SET @CPF = '5576228758'
SET @ANO = 2016
SET @DENOMINADOR = 0
SET @MENSAGEM = ''
 
--Executando
EXEC TrataErroZeroTry @CPF = @CPF, @ANO = @ANO, @DENOMINADOR = @DENOMINADOR, @MENSAGEM = @MENSAGEM OUTPUT

-- Exibe mensagem se houver erro
IF @MENSAGEM <> ''
	PRINT @MENSAGEM