-->> LOOP PARA INSERIR REGISTROS EM UMA TABELA <<--

-- Insere numeros em tabela de acordo com o limite definido 
-- e um status verificando se o número corresponde 
-- a uma nota fiscal

--DROPA a tabela caso já exista 
USE SUCOS_VENDAS  

IF OBJECT_ID('TABELA DE NUMEROS', 'U') IS NOT NULL
	DROP TABLE [TABELA DE NUMEROS]


CREATE TABLE [TABELA DE NUMEROS]
	([NUMERO] INT, [STATUS] VARCHAR(200))

DECLARE @LIMITE_MAXIMO INT
DECLARE @LIMITE_MINIMO INT
DECLARE @CONTADOR_NOTAS INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 1000


--Não exibe resultado a cada insert em 'results'
SET NOCOUNT ON

WHILE @LIMITE_MAXIMO >= @LIMITE_MINIMO
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE NUMERO = @LIMITE_MINIMO
	IF @CONTADOR_NOTAS > 0
		INSERT INTO [TABELA DE NUMEROS] ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'É nota fiscal')
	ELSE
		INSERT INTO [TABELA DE NUMEROS] ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'NÃO é nota fiscal')
	SET @LIMITE_MINIMO = @LIMITE_MINIMO +1
END


SELECT * FROM [TABELA DE NUMEROS]
SELECT * FROM [NOTAS FISCAIS]
	